// Code generated by go generate; DO NOT EDIT.
// Generated with ❤ by github.com/shanna/phrasebook
// TODO(shane): Filename.
// 2019-01-01 22:14:08.213083 +0000 GMT m=+0.002496794
package TODO(shane): Package.

// 
const TestExportCGO = "select * from test_export_cgo where \"id\" = @id;"

// test
// baz
const TestExportPhrasebook = "select\n  *\nfrom\n  test_export_phrasebook\nwhere\n  id = @id;"

// woot
const TestExportYesql = "select *\nfrom test_export_yesql\nwhere id = @id;"

